- hosts: localhost
  tasks:

    - name: debug vms ips
      debug:
        msg: "{{ vm_ips }}"

    - name: Add VMs to inventory
      import_tasks: ../playbooks/tasks/inventory-add-vms.yml

    - name: Make sure VMs are running
      import_tasks: ../playbooks/tasks/vm-started.yml


- hosts: checker
  become: true
  tasks:

    - name: Trasferisci filechecker jar
      ansible.builtin.copy:
        src: "{{ local_working_directory }}{{ local_ranflood_files_dir }}{{ name_filechecker_jar }}"
        dest: "{{ path_filechecker }}"
        force: transfer_filechecker

    - name: Crea mounting point per Windows
      ansible.builtin.file:
        path: "{{ path_mnt_win }}"
        state: directory

    - name: Crea mounting point storage condiviso
      ansible.builtin.file:
        path: /mnt/shared
        state: directory

    - name: Monta disco Windows
      ansible.posix.mount:
        path: "{{ path_mnt_win }}"
        src: /dev/sdb1
        state: mounted
        fstype: ntfs

    - name: Crea partizione storage condiviso
      community.general.parted:
        device: /dev/sdc
        number: 1
        state: present

    - name: Formatta partizione storage condiviso
      community.general.filesystem:
        dev: /dev/sdc1
        fstype: ext4

    - name: Monta storage condiviso
      ansible.posix.mount:
        path: /mnt/shared
        src: /dev/sdc1
        state: mounted
        fstype: ext4

    - name: Filechecker check
      ansible.builtin.command:
        cmd: java -jar {{ path_filechecker }} check /home/checker/cleanWindowsChecksum /home/checker/report {{ target_dir }}
        chdir: dir_filechecker
      when: do_check

    - name: Filechecker sss restore
      ansible.builtin.command:
        cmd: java -jar {{ path_filechecker }} restore /home/checker/cleanWindowsChecksum /home/checker/report {{ target_dir }}
        chdir: "{{ dir_filechecker }}"
      when: do_restore and not restore_delete

    - name: Filechecker sss restore with delete
      ansible.builtin.command:
        cmd: java -jar {{ path_filechecker }} restore /home/checker/cleanWindowsChecksum /home/checker/report {{ target_dir }} --delete
        chdir: "{{ dir_filechecker }}"
      when: do_restore and restore_delete

    - name: Trasferisci report nello storage condiviso
      ansible.builtin.copy:
        src: /home/checker/report
        dest: /mnt/shared/
        remote_src: true
      when: do_check or do_restore

    - name: Smonta disco Windows
      ansible.posix.mount:
        path: "{{ path_mnt_win }}"
        state: unmounted

    - name: Smonta storage condiviso
      ansible.posix.mount:
        path: /mnt/shared
        state: unmounted

