- hosts: checker
  become: true
  tasks:

    - name: Crea mounting point per Windows
      ansible.builtin.file:
        path: /mnt/win10
        state: directory

    - name: Crea mounting point storage condiviso
      ansible.builtin.file:
        path: /mnt/shared
        state: directory

    - name: Monta disco Windows
      ansible.posix.mount:
        path: /mnt/win10
        src: /dev/sdb1
        state: mounted
        fstype: ntfs

    - name: Crea partizione storage condiviso
      community.general.parted:
        device: /dev/sdc
        number: 1
        state: present

    - name: Formatta partizione storage condiviso
      community.general.filesystem:
        dev: /dev/sdc1
        fstype: ext4

    - name: Monta storage condiviso
      ansible.posix.mount:
        path: /mnt/shared
        src: /dev/sdc1
        state: mounted
        fstype: ext4

    - name: Esegui filechecker
      ansible.builtin.command:
        cmd: java -jar filechecker.jar check /home/checker/cleanWindowsChecksum /home/checker/report /mnt/win10/Users/IEUser
        chdir: /home/checker/ranflood-master/build/libs

    - name: Trasferisci report nello storage condiviso
      ansible.builtin.copy:
        src: /home/checker/report
        dest: /mnt/shared/
        remote_src: true

    - name: Smonta disco Windows
      ansible.posix.mount:
        path: /mnt/win10
        state: unmounted

    - name: Smonta storage condiviso
      ansible.posix.mount:
        path: /mnt/shared
        state: unmounted

  hosts: proxmox
  tasks:

 - name: Attendi
   ansible.builtin.pause:
     seconds: "{{ attesa_spegnimento }}"

 - name: spegni vm
   ansible.builtin.command: qm shutdown {{ item }}
   loop: "{{ vm_ids }}"