#!/bin/bash


# timestamp, can be used as "unique" id
timestamp: '20250318-16_16_48'


# Script

# for downloading binaries
ranflood_download: 'https://github.com/Flooding-against-Ransomware/ranflood/releases/download/v.0.7-beta/ranflood-v.0.7-beta_Windows.zip'
# WannaCry
#ransomware_download_link: '${#ransomware_download_link}'
# Phobos
#ransomware_download_link: '${#ransomware_download_link}'


# Ansible

local_working_directory: '/home/papum/programm/unibo/projects/SAFARI/ansible/'

## subdirectory of `local_working_directory` containing ranflood files to transfer
local_path_files_checker: 'files/checker'
local_path_files_prepopulate: 'files/prepopulate'
local_path_files_ranflood: 'files/ranflood'
local_path_files_ransomwares: 'files/ransomwares'
local_path_files_transfer: 'files/transfer'

## where all files will be transferred (except ranflood)
remote_working_directory_win: 'C:\Users\'
remote_working_directory_linux: '/mnt/c/Users/'

remote_working_directory_checker: '/home/checker/'


# Files (ansible)
## all of these files will be transferred

dir_variables: 'variables/'

name_internal_playbook: 'internal_playbook.yml'
#name_internal_playbook: '${#name_internal_playbook}'
name_internal_inventory: 'internal_inventory'
name_ansible_variables: 'variables.generated.yml'
name_ansible_variables_internal: 'variables_internal.yml'


# Files (ranflood, ransomwares)
## all of these files will be transferred, except for ransomwares

## ranflood
name_filechecker_jar: 'filechecker.jar'
name_ranflood: 'ranflood.exe'
name_ranfloodd: 'ranfloodd.exe'
name_ranflood_bat: 'ranflood.bat'
name_ranfloodd_bat: 'ranfloodd.bat'
name_ranflood_jar: 'ranflood.jar'
name_ranfloodd_jar: 'ranfloodd.jar'
#name_ranflood_zip: '${#name_ranflood_zip}'
name_ranflood_zip: 'ranflood-v.0.6-beta_Windows_client.zip'

## configs
name_settings_ini: 'settings.ini'
name_vcruntime140_1_dll: 'vcruntime140_1.dll'

## for scripts to execute on the remote hosts
name_prepopulate_script: 'prepopulate.sh'
name_prepopulate_script_win: 'prepopulate.bat'
name_env_windows: 'variables.generated.bat'
name_env_linux: 'variables.generated.sh'

## ransomwares
## (only this one will be transferred and used)

# Locbkit
name_ransomware: 'lockbit'
# Petya
#name_ransomware: '${#name_ransomware}'
# Phobos
#name_ransomware: '${#name_ransomware}'
# Vipasana
#name_ransomware: '${#name_ransomware}'
# WannaCry
#name_ransomware: '${#name_ransomware}'
# WannaCry_plus
#name_ransomware: '${#name_ransomware}'
# java Ransomware
#name_ransomware: '${#name_ransomware}'

#name_ransomware_zip: '${#name_ransomware_zip}'
name_ransomware_zip: 'lockbit.7z'

### transfer the java Ransomware instead
#name_ransomware_zip: '${#name_ransomware_zip}'

name_ransomware_dir_win: 'ransomware\'


# Config, execution

## where ranflood files are or will be put (windows)
path_ranflood_dir_win: 'C:\Program Files\Ranflood\'

path_ranflood_win: 'C:\Program Files\Ranflood\ranflood.exe'
path_ranfloodd_win: 'C:\Program Files\Ranflood\ranfloodd.exe'
path_ranflood_bat: 'C:\Users\ranflood.bat'
path_ranfloodd_bat: 'C:\Users\ranfloodd.bat'
path_ranflood_jar_win: 'C:\Program Files\Ranflood\ranflood.jar'
path_ranfloodd_jar_win: 'C:\Program Files\Ranflood\ranfloodd.jar'
path_ransomware_win: 'C:\Users\lockbit'
path_ransomware_dir_win: 'C:\Users\ransomware\'
path_settings_ini_win: 'C:\Users\settings.ini'

## where ranflood files are or will be put (wsl)
path_ranflood_dir_linux: '/mnt/c/Program Files/Ranflood/'

path_ranflood_linux: '/mnt/c/Program Files/Ranflood/ranflood.exe'
path_ranfloodd_linux: '/mnt/c/Program Files/Ranflood/ranfloodd.exe'
path_ranflood_jar_linux: '/mnt/c/Program Files/Ranflood/ranflood.jar'
path_ranfloodd_jar_linux: '/mnt/c/Program Files/Ranflood/ranfloodd.jar'
path_ransomware_linux: '/mnt/c/Users/lockbit'
path_settings_ini_linux: '/mnt/c/Users/settings.ini'

path_checker_out_dir: '/home/checker/20250318-16_16_48/'

## where output of internal playbook is saved
path_log_win: 'C:\Users\log20250318-16_16_48.txt'
path_log_linux: '/mnt/c/Users/log20250318-16_16_48.txt'
## log of filechecker restore command
path_log_filechecker: '/home/checker/20250318-16_16_48/log20250318-16_16_48.txt'
path_log_filechecker_out: '/home/checker/20250318-16_16_48/out20250318-16_16_48.txt'
path_log_internal_daemon: 'C:\Users\log_daemon20250318-16_16_48.txt'
path_log_internal_ransomware: 'C:\Users\log_ransomware20250318-16_16_48.txt'

path_report: '/home/checker/20250318-16_16_48/report20250318-16_16_48'
path_report_shards: '/home/checker/20250318-16_16_48/report-shards20250318-16_16_48'


# Prepopulate

## seconds for which to run ranflood random to prepopulate the disk
ranflood_random_duration: '3'
## stop prepopulating with random when less of KB of free space is available
ranflood_random_remaining_space_kb: '1000000'

## target dir to prepopulate with random files (through prepopulate.sh)
ranflood_random_target_dir: 'C:\Users\IEUser\Documents\'
ranflood_random_target_dir_linux: '/mnt/c/Users/IEUser/Documents/'

