#!/bin/bash


# timestamp, can be used as "unique" id
timestamp: '20250103-17_44_45'


# Script

# for downloading binaries
ranflood_download: 'https://github.com/Flooding-against-Ransomware/ranflood/releases/download/v.0.7-beta/ranflood-v.0.7-beta_Windows.zip'
# WannaCry
#ransomware_download_link: '${#ransomware_download_link}'
# Phobos
#ransomware_download_link: '${#ransomware_download_link}'


# Ansible

local_working_directory: '/home/papum/programm/unibo/projects/SAFARI/ansible/'

# subdirectory of `local_working_directory` containing ranflood files to transfer
local_path_files_checker: 'files/checker'
local_path_files_prepopulate: 'files/prepopulate'
local_path_files_ranflood: 'files/ranflood'
local_path_files_ransomwares: 'files/ransomwares'
local_path_files_transfer: 'files/transfer'

# where all files will be transferred
remote_working_directory_win: 'C:\Users\'
remote_working_directory_linux: '/mnt/c/Users/'


# Files to transfer (ansible)

# avoid transfers if already exists
transfer_force: 'false'

dir_variables: 'variables/'

name_internal_playbook: 'internal_playbook.yml'
name_internal_inventory: 'internal_inventory'
name_internal_variables: 'internal_inventory'
name_ansible_variables: 'variables.generated.yml'
name_ansible_variables_internal: 'variables_internal.yml'


# Files to transfer (ranflood, ransomwares)

name_filechecker_jar: 'filechecker.jar'
name_ranflood: 'ranflood.exe'
name_ranfloodd: 'ranfloodd.exe'
name_ranflood_bat: 'ranflood.bat'
name_ranfloodd_bat: 'ranfloodd.bat'
name_ranflood_jar: 'ranflood.jar'
name_ranfloodd_jar: 'ranfloodd.jar'
#name_ranflood_zip: '${#name_ranflood_zip}'
name_ranflood_zip: 'ranflood-v.0.6-beta_Windows_client.zip'

# WannaCry
#name_ransomware: '${#name_ransomware}'
# Phobos
name_ransomware: 'phobos.bin'

name_ransomware_zip: 'phobos.bin.zip'

name_settings_ini: 'settings.ini'

name_vcruntime140_1_dll: 'vcruntime140_1.dll'

## for scripts to execute on the remote hosts
name_prepopulate_script: 'prepopulate.sh'
name_prepopulate_script_win: 'prepopulate.bat'
name_env_windows: 'variables.generated.bat'
name_env_linux: 'variables.generated.sh'


# Config, execution

path_ranflood_dir_win: 'C:\Program Files\Ranflood\'
path_ranflood_win: 'C:\Program Files\Ranflood\ranflood.exe'
path_ranfloodd_win: 'C:\Program Files\Ranflood\ranfloodd.exe'
path_ranflood_bat: 'C:\Users\ranflood.bat'
path_ranfloodd_bat: 'C:\Users\ranfloodd.bat'
path_ranflood_jar_win: 'C:\Program Files\Ranflood\ranflood.jar'
path_ranfloodd_jar_win: 'C:\Program Files\Ranflood\ranfloodd.jar'
path_ransomware_win: 'C:\Users\phobos.bin'
path_settings_ini_win: 'C:\Users\settings.ini'

path_ranflood_dir_linux: '/mnt/c/Program Files/Ranflood/'
path_ranflood_linux: '/mnt/c/Program Files/Ranflood/ranflood.exe'
path_ranfloodd_linux: '/mnt/c/Program Files/Ranflood/ranfloodd.exe'
path_ranflood_jar_linux: '/mnt/c/Program Files/Ranflood/ranflood.jar'
path_ranfloodd_jar_linux: '/mnt/c/Program Files/Ranflood/ranfloodd.jar'
path_ransomware_linux: '/mnt/c/Users/phobos.bin'
path_settings_ini_linux: '/mnt/c/Users/settings.ini'

# where output of internal playbook is saved
path_log_linux: '/mnt/c/Users/log20250103-17_44_45.txt'
# log of filechecker restore command
path_log_filechecker: '/home/checker/log20250103-17_44_45.txt'
path_log_internal_daemon: 'C:\Users\log_daemon20250103-17_44_45.txt'

# seconds for which to run ranflood random to prepopulate the disk
ranflood_random_duration: '3'
# stop prepopulating with random when less of KB of free space is available
ranflood_random_remaining_space_kb: '1000000'

# target dir to prepopulate with random files (through prepopulate.sh)
ranflood_random_target_dir: 'C:\Users\IEUser\Documents\'
ranflood_random_target_dir_linux: '/mnt/c/Users/IEUser/Documents/'

