#!/bin/bash

dir_current=$(pwd)
dir_ansible=ansible/

# variables
variables_user=variables.sh
variables_checker=variables-checker.yml
variables_credentials=variables-credentials.generated.secret.yml
variables_vm_ids=variables-vm-ids.generated.yml
variables_vm_ips=variables-vm-ips.generated.yml
variables_vm_ids_user=variables-vm-ids.yml
variables_vm_ips_user=variables-vm-ips.yml

function usage() {
	echo "launch-ansible-checker.sh: Launch the ansible playbooks for the filechecker."
	echo "	${variables_vm_ids}, ${variables_vm_ips} can be automatically generated by 'scripts/launch.sh --checker' or 'scripts/read-vms.sh -c', from the terraform output;"
	echo "	however, if ${variables_vm_ids_user}, ${variables_vm_ips_user} are found, they are used instead."
	echo "Usage: ./scripts/launch-ansible-checker.sh"
	echo ""
	echo "  Warning: this script will download a zipped ransomware."
	exit 1
}


# Check current dir

if [[ ! -d ${dir_ansible} ]]; then
	echo "Directory ${dir_ansible} not found. Make sure to run this command from the project's root directory."
	usage
else
	cd ${dir_ansible}
fi

# Check args

## Required files
required_files=( \
	"checker/playbook.yml" \
	"checker/inventory" \
	"checker/${variables_checker}" \
)

for file in "${required_files[@]}"; do
    if [[ ! -f $file ]]; then
		echo "$file not found."
        usage
    fi
done


# Set variables

set -a

source variables/${variables_user}

cd ${dir_current}
./scripts/generate.sh
cd ${dir_ansible}


# Run ansible

ansible-playbook -i checker/inventory checker/playbook.yml \
	--extra-vars "@variables/${name_ansible_variables}" \
	--extra-vars "@variables/${variables_credentials}" \
	--extra-vars "@checker/${variables_checker}" \
	--extra-vars "@checker/${variables_vm_ids}" \
	--extra-vars "@checker/${variables_vm_ips}"
