#!/bin/bash

dir_current=$(pwd)
dir_ansible=ansible/

# variables
dir_variables=variables/
variables_user=variables.sh
variables_external=variables_external.yml
variables_credentials=variables-credentials.generated.secret.yml
variables_vm_ids=variables-vm-ids.generated.yml
variables_vm_ips=variables-vm-ips.generated.yml
variables_vm_ids_user=variables-vm-ids.yml
variables_vm_ips_user=variables-vm-ips.yml

function usage() {
	echo "launch-ansible.sh: Launch the ansible playbooks."
	echo "	${variables_vm_ids}, ${variables_vm_ips} can be automatically generated by scripts/launch.sh or scripts/util/read-vms.sh, from the terraform output;"
	echo "	however, if ${variables_vm_ids_user}, ${variables_vm_ips_user} are found, they are used instead."
	echo "Usage: ./scripts/launch-ansible.sh [-y]"
	echo "  -y: skip warning"
	echo ""
	echo "  Warning: this script will download a zipped ransomware."
	exit 1
}


# Check current dir

if [[ ! -d ${dir_ansible} ]]; then
	echo "Directory ${dir_ansible} not found. Make sure to run this command from the project's root directory."
	usage
else
	cd ${dir_ansible}
	pwd
fi

# Check args

## Required files
required_files=( \
	"full_playbook.yml" \
	"internal_inventory" \
	"internal_playbook.yml" \
	"${dir_variables}${variables_external}" \
)

for file in "${required_files[@]}"; do
    if [[ ! -f $file ]]; then
		echo "$file not found."
        usage
    fi
done

## Args

skip_warning=false
while getopts "y" opt; do
    case $opt in
        y)
            skip_warning=true
            ;;
        *)
            echo "Invalid option: -$OPTARG" >&2
			usage
            exit 1
            ;;
    esac
done

# Ask user if they want to continue with the download
if ! $skip_warning; then
    read -p "Warning: This script will download a ransomware. Do you want to continue? (y/n): " choice
    case "$choice" in 
      y|Y ) echo "Continuing...";;
      n|N ) echo "Exiting..."; exit 0;;
      * ) echo "Invalid choice."; usage;;
    esac
fi


# Set variables

set -a

# source variables (also used for ansible)
source ${dir_variables}${variables_user}

cd ${dir_current}
./scripts/util/generate.sh
cd ${dir_ansible}


# Downloads

cd ${local_working_directory}/${local_path_files_ranflood}

if [[ ! -f ${name_ranflood_zip} ]]; then
	echo "[Download] Downloading ranflood..."
	curl -L -o ${name_ranflood_zip} ${ranflood_download}
else
	echo "[Download] ${name_ranflood_zip} already downloaded"
fi

cd ${local_working_directory}
cd ${local_working_directory}/${local_path_files_ransomwares}
if [[ ! -f ${name_ransomware_zip} ]]; then
	echo "[Download] Can't download ransomware."
	echo "[Download] Missing ransomware. Please put it manually in ansible/files/ransomwares/ ."
	exit 1
	#echo "[Download] Downloading ${name_ransomware_zip}..."
	#curl -L -o ${name_ransomware_zip} ${ransomware_download_link}
else
	echo "[Download] ${name_ransomware_zip} already downloaded"
fi

cd ${local_working_directory}


# Run ansible

## debug up to -vvvvvv (x6)
ansible-playbook -v -i external_inventory full_playbook.yml \
	--extra-vars "@${dir_variables}${name_ansible_variables}" \
	--extra-vars "@${dir_variables}${variables_external}" \
	--extra-vars "@${dir_variables}${variables_credentials}" \
	--extra-vars "@${dir_variables}${variables_vm_ids}" \
	--extra-vars "@${dir_variables}${variables_vm_ips}"
