#/******************************************************************************
# * Copyright 2021 (C) by Tommaso Compagnucci <tommasocompagnucci1@gmail.com>  *
# *                                                                            *
# * This program is free software; you can redistribute it and/or modify       *
# * it under the terms of the GNU Library General Public License as            *
# * published by the Free Software Foundation; either version 2 of the         *
# * License, or (at your option) any later version.                            *
# *                                                                            *
# * This program is distributed in the hope that it will be useful,            *
# * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
# * GNU General Public License for more details.                               *
# *                                                                            *
# * You should have received a copy of the GNU Library General Public          *
# * License along with this program; if not, write to the                      *
# * Free Software Foundation, Inc.,                                            *
# * 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.                  *
# *                                                                            *
# * For details about the authors of this software, see the AUTHORS file.      *
# ******************************************************************************/

- hosts: localhost
  tasks:

    - name: Aggiungi VM all'inventario
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: windows
      loop: "{{ new_ip }}"

- hosts: windows
  tasks:

    - name: Hello world
      ansible.builtin.debug:
        msg: "Hello world!"

#    - name: Trasferisci ransomware compresso
#      ansible.windows.win_copy:
#        src: "{{ local_working_directory }}{{ ransomware_name }}"
#        dest: "{{ remote_windows_user_directory }}{{ ransomware_name }}"
#
#    - name: Trasferisci playbook interno
#      ansible.windows.win_copy:
#        src: "{{ local_working_directory }}{{ internal_playbook_name }}"
#        dest: "{{ remote_windows_user_directory }}{{ internal_playbook_name }}"
#
#    - name: Trasferisci inventario Ansible
#      ansible.windows.win_copy:
#        src: "{{ local_working_directory }}{{ internal_inventory_name }}"
#        dest: "{{ remote_windows_user_directory }}{{ internal_inventory_name }}"
#
#    - name: Trasferisci file variabili ansible
#      ansible.windows.win_copy:
#        src: "{{ local_working_directory }}{{ ansible_variables_path }}"
#        dest: "{{ remote_windows_user_directory }}{{ ansible_variables_path }}"
#
#    - name: Trasferisci script prepopulate
#      ansible.windows.win_copy:
#        src: "{{ local_working_directory }}{{ ranflood_prepopulate_batch }}"
#        dest: "{{ remote_windows_user_directory }}{{ ranflood_prepopulate_batch }}"
#
#    - name: Avvia playbook interno
#      ansible.windows.win_command: wsl ansible-playbook -i {{ remote_linux_user_directory }}{{ internal_inventory_name }} {{ remote_linux_user_directory }}{{ internal_playbook_name }} --extra-vars "@{{ remote_linux_user_directory }}{{ ansible_variables_path }}"
#      async: 3600
#      poll: 0
#
#
#- hosts: proxmox
#  tasks:
#
#  - name: Attendi
#    ansible.builtin.pause:
#      seconds: "{{ attesa_spegnimento }}"
#
#  - name: spegni vm
#    ansible.builtin.command: qm shutdown {{ item }}
#    loop: "{{ vm_id }}"