#/******************************************************************************
# * Copyright 2021 (C) by Tommaso Compagnucci <tommasocompagnucci1@gmail.com>  *
# *                                                                            *
# * This program is free software; you can redistribute it and/or modify       *
# * it under the terms of the GNU Library General Public License as            *
# * published by the Free Software Foundation; either version 2 of the         *
# * License, or (at your option) any later version.                            *
# *                                                                            *
# * This program is distributed in the hope that it will be useful,            *
# * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
# * GNU General Public License for more details.                               *
# *                                                                            *
# * You should have received a copy of the GNU Library General Public          *
# * License along with this program; if not, write to the                      *
# * Free Software Foundation, Inc.,                                            *
# * 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.                  *
# *                                                                            *
# * For details about the authors of this software, see the AUTHORS file.      *
# ******************************************************************************/

- hosts: windows
  tasks:

  - name: Remove network adapter
    community.windows.win_net_adapter_feature:
      interface: '*'
      state: disabled
      component_id:
        - ms_tcpip
        - ms_tcpip6
        - ms_implat
        - ms_lltdio
        - ms_rspndr
        - ms_lldp
        - ms_msclient
        - ms_pacer

  - name: Start ranflood daemon
    ansible.windows.win_command: 
      argv:
        - "{{ path_ranfloodd }}"
        - "{{ path_settings_ini }}"
    async: 1800
    poll: 0

  - name: Wait for ranflood daemon
    ansible.builtin.pause:
      seconds: "{{ ranflood_start_delay }}"

  - name: Prepopulate the disk using Ranflood Random
    ansible.windows.win_command: 
      argv:
        - "{{ path_ranflood }}"
        - flood 
        - start
        - random
        - "{{ ranflood_target_dir }}"

  - name: Let Random run
    ansible.builtin.pause:
      seconds: "{{ ranflood_random_duration }}"

  - name: Stop Ranflood Random
    ansible.windows.win_command: 
      argv:
        - "{{ path_ranflood }}"
        - flood 
        - start
        - random
        - "{{ ranflood_target_dir }}"

  

