#/******************************************************************************
# * Copyright 2021 (C) by Tommaso Compagnucci <tommasocompagnucci1@gmail.com>  *
# *                                                                            *
# * This program is free software; you can redistribute it and/or modify       *
# * it under the terms of the GNU Library General Public License as            *
# * published by the Free Software Foundation; either version 2 of the         *
# * License, or (at your option) any later version.                            *
# *                                                                            *
# * This program is distributed in the hope that it will be useful,            *
# * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
# * GNU General Public License for more details.                               *
# *                                                                            *
# * You should have received a copy of the GNU Library General Public          *
# * License along with this program; if not, write to the                      *
# * Free Software Foundation, Inc.,                                            *
# * 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.                  *
# *                                                                            *
# * For details about the authors of this software, see the AUTHORS file.      *
# ******************************************************************************/


- hosts: localhost
  tasks:
  #- name: Create a JIRA issue
  #  ansible.builtin.uri:
  #    url: https://192.168.2.14:8006/api2/json/nodes/pve4/qemu/402/status/shutdown
  #    method: POST
  #    body: "{{ lookup('ansible.builtin.file','issue.json') }}"
  #    force_basic_auth: true
  #    status_code: 201
  #    body_format: json

    # requirements:
    # ansible-galaxy collection install community.general
    # apt install python3-proxmoxer
    #- name: Stop container with force
    #  community.general.proxmox:
    #    vmid: 110
    #    api_host: 192.168.2.17
    #    api_port: 8006
    #    api_user: 
    #    api_token_id: 
    #    api_token_secret:
    #    node: pve7
    #    #force: true
    #    state: started


    - name: Create new container automatically selecting the next available vmid.
      community.general.proxmox_kvm:
        vmid: 110
        node: 'pve7'
        api_user: 
        api_token_id: 
        api_token_secret: 
        api_host: 192.168.2.17
        api_port: 8006
        state: stopped
        force: true
